<?php
$title = "Neverball";
include("includes/header.php");
?>
<main id="main">
	<div id="contents">

		<h2>News</h2>
		
		<div>
			<article>
				<h3>More curves? Yes, please! <time datetime="2025-04-03">April 3, 2025</time></h3>

				<p>
					MightyBurger on the Neverball Discord has released a new curve generation tool for Neverball mappers. It's called <a href="https://github.com/MightyBurger/curveball?tab=readme-ov-file#curveball" target="_blank">curveball</a> and you can run it <a href="https://curveball.mightyburger.net/" target="_blank">in your browser</a>. The screenshots are crazy, here's just one of them:
				</p>

				<p>
					<a href="https://github.com/MightyBurger/curveball?tab=readme-ov-file#curveball" target="blank">
						<img src="./images/curveball-teaser.png" width="800" height="354" alt="Examples of curves generated by the curveball tool.">
					</a>
				</p>

				<p>
					If you're interested in how the tool was made, MightyBurger has got you covered with a <a href="https://mightyburger.net/projects/curveball/">blog post</a> on that very topic.
				</p>

				<p>
					Now, let's get mapping!
				</p>

			</article>

			<article>
				<h3>Neverball 1.6.0 <time datetime="2014-05-21">May 21, 2014</time></h3>

				<div>
					<p>Neverball 1.6.0 is out now! Get it from the <a href="download.php">download page</a> and have a look at the <a href="release.php">release notes</a>.</p>
					<p>Long-time contributor Cheeseness has put together a <a href="images/neverball_poster_1.6.0.png">poster</a> and an <a href="https://www.youtube.com/watch?v=ZQ9VDabHGpA">introductory video</a> to celebrate the release. We also have a <a href="https://www.youtube.com/watch?v=bQqK2YuP2Tc">video on Oculus Rift support</a> from Robert Kooima, the lead developer of Neverball. Be sure to check them out!</p>
				</div>
			</article>
		</div>

		<h2>About</h2>
		<p>Tilt the floor to roll a ball through an obstacle course before time runs out. Neverball is part puzzle game, part action game, and entirely a test of skill.</p>
		<p>Also found here is Neverputt, a hot-seat multiplayer miniature golf game, built on the physics and graphics engine of Neverball.</p>
		<p>Neverball is known to run under Linux, Windows, FreeBSD, and Mac OSX. Hardware accelerated OpenGL is required. A modern processor is recommended.</p>

		<h2>Community &amp; Contact</h2>
		<p>Visit the community <a href="https://discord.gg/HhMfr4N6H6">Neverball Discord</a> server to get in touch with other players and designers.</p>
		<p>We are also on <a href="https://github.com/Neverball">Github</a> (be sure to check out the <a href="https://github.com/Neverball/neverball/discussions">discussions</a> section) and <a href="https://steamcommunity.com/groups/neverball">Steam</a>.</p>

		<h2>Level Design</h2>
		<p>Players interested in trying their hand at level creation are encouraged to read through the <a href="http://github.com/neverball/neverball-docs">level design documentation</a>. Levels of sufficent quality may be included in the next version; authors will be credited in-game.</p>
	</div>
</main>

<?php
include("includes/footer.php");
