<?php
$title = "Neverball";
$description = "Neverball is a free, open-source skill and puzzle game. Tilt the floor to roll through obstacle courses. Play right away in your browser or download for desktop.";
include("includes/header.php");
?>
<main id="main">
	<section id="hero" aria-label="Neverball overview">
		<div id="screenshot">
			<video src="/images/anim.mp4" poster="/images/anim.jpg" width="640" height="360" loop muted autoplay playsinline title="Neverball gameplay preview" aria-label="Neverball gameplay preview"></video>
		</div>

		<h2><span class="neverball-text">Tilt the floor. Roll the ball. Beat the clock!</span></h2>

		<p class="text-sm leading-relaxed">
			<strong>Neverball</strong> is a free, open-source skill and puzzle game. Guide your ball through precarious obstacle courses before time runs out by tilting the world beneath it. Play right away in your web browser or download the desktop version which also includes <strong>Neverputt</strong>, the companion hot-seat miniature golf game.
		</p>

		<div class="hero-actions flex flex-wrap gap-2 items-center">
			<a href="https://play.neverball.org" target="_blank" class="neverball-button update-button-focused">Play in Browser</a>
			<a href="/download" class="neverball-button">Download Neverball</a>
		</div>

		<p class="text-xs text-muted">
			Free &amp; open-source for Linux, Windows, macOS, and FreeBSD.
		</p>
	</section>

	<script type="application/ld+json">
	{
		"@context": "https://schema.org",
		"@type": "VideoGame",
		"name": "Neverball",
		"description": "Neverball is a free, open-source 3D skill and puzzle game. Tilt the floor to roll a ball through obstacle courses before time runs out.",
		"url": "<?php echo BASE_URL; ?>",
		"image": "<?php echo BASE_URL; ?>/images/anim.jpg",
		"genre": ["Puzzle", "Action", "Skill"],
		"gamePlatform": ["Web Browser", "Linux", "Windows", "macOS", "FreeBSD"],
		"applicationCategory": "Game",
		"offers": {
			"@type": "Offer",
			"price": "0",
			"priceCurrency": "USD"
		}
	}
	</script>

	<div id="contents">
		<h2>News</h2>
		
		<div>
			<article>
				<h3>More curves? Yes, please! <time datetime="2025-04-03">April 3, 2025</time></h3>

				<p>
					MightyBurger on the Neverball Discord has released a new curve generation tool for Neverball mappers. It's called <a href="https://github.com/MightyBurger/curveball?tab=readme-ov-file#curveball" target="_blank">curveball</a> and you can run it <a href="https://curveball.mightyburger.net/" target="_blank">in your browser</a>. The screenshots are crazy, here's just one of them:
				</p>

				<p>
					<a href="https://github.com/MightyBurger/curveball?tab=readme-ov-file#curveball" target="blank">
						<img src="./images/curveball-teaser.png" width="800" height="354" alt="Examples of curves generated by the curveball tool.">
					</a>
				</p>

				<p>
					If you're interested in how the tool was made, MightyBurger has got you covered with a <a href="https://mightyburger.net/projects/curveball/">blog post</a> on that very topic.
				</p>

				<p>
					Now, let's get mapping!
				</p>

			</article>

			<article>
				<h3>Neverball 1.6.0 <time datetime="2014-05-21">May 21, 2014</time></h3>

				<div>
					<p>Neverball 1.6.0 is out now! Get it from the <a href="download.php">download page</a> and have a look at the <a href="release.php">release notes</a>.</p>
					<p>Long-time contributor Cheeseness has put together a <a href="images/neverball_poster_1.6.0.png">poster</a> and an <a href="https://www.youtube.com/watch?v=ZQ9VDabHGpA">introductory video</a> to celebrate the release. We also have a <a href="https://www.youtube.com/watch?v=bQqK2YuP2Tc">video on Oculus Rift support</a> from Robert Kooima, the lead developer of Neverball. Be sure to check them out!</p>
				</div>
			</article>
		</div>

		<h2>Community &amp; Contact</h2>
		<p>Visit the community <a href="https://discord.gg/HhMfr4N6H6">Neverball Discord</a> server to get in touch with other players and designers.</p>
		<p>We are also on <a href="https://github.com/Neverball">Github</a> (be sure to check out the <a href="https://github.com/Neverball/neverball/discussions">discussions</a> section) and <a href="https://steamcommunity.com/groups/neverball">Steam</a>.</p>

		<h2>Level Design</h2>
		<p>Players interested in trying their hand at level creation are encouraged to read through the <a href="http://github.com/neverball/neverball-docs">level design documentation</a>. Levels of sufficent quality may be included in the next version; authors will be credited in-game.</p>
	</div>
</main>

<?php
include("includes/footer.php");
